# Generated by Django 2.0.6 on 2018-06-15 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180614_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='folloings',
            field=models.ManyToManyField(related_name='_user_folloings_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
